services:
  mysql_container:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mysql-data:/var/lib/mysql

  node_app:
    build: .
    container_name: node_app
    ports:
      - "3000:3000"
    depends_on:
      - mysql_container
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: ["./wait-for-it.sh", "mysql_container:3306", "--", "node", "code.js"]


volumes:
  mysql-data:
